CREATE TABLE IF NOT EXISTS tw_facturacion_pac_audit (
    n_id BIGINT NOT NULL AUTO_INCREMENT,
    d_fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    s_fecha_operacion VARCHAR(80) DEFAULT NULL,
    s_operacion VARCHAR(100) NOT NULL,
    s_proveedor VARCHAR(60) DEFAULT NULL,
    s_endpoint VARCHAR(255) DEFAULT NULL,
    s_metodo_http VARCHAR(10) DEFAULT NULL,
    s_request_json LONGTEXT DEFAULT NULL,
    s_response_json LONGTEXT DEFAULT NULL,
    n_http_status INT DEFAULT NULL,
    b_success TINYINT(1) DEFAULT NULL,
    s_error_code VARCHAR(120) DEFAULT NULL,
    s_error_message VARCHAR(1000) DEFAULT NULL,
    s_correlation_id VARCHAR(100) DEFAULT NULL,
    s_uuid_relacionado VARCHAR(80) DEFAULT NULL,
    n_razon_social_id BIGINT DEFAULT NULL,
    n_id_venta BIGINT DEFAULT NULL,
    s_rfc_emisor VARCHAR(20) DEFAULT NULL,
    s_usuario VARCHAR(120) DEFAULT NULL,
    s_metadata_json LONGTEXT DEFAULT NULL,
    PRIMARY KEY (n_id),
    KEY idx_tw_facturacion_pac_audit_fecha (d_fecha_registro),
    KEY idx_tw_facturacion_pac_audit_uuid (s_uuid_relacionado),
    KEY idx_tw_facturacion_pac_audit_venta (n_id_venta),
    KEY idx_tw_facturacion_pac_audit_razon (n_razon_social_id),
    KEY idx_tw_facturacion_pac_audit_correlation (s_correlation_id)
);