CREATE TABLE IF NOT EXISTS tw_facturacion_complemento_pago (
    n_id BIGINT NOT NULL AUTO_INCREMENT,
    n_id_venta BIGINT NOT NULL,
    n_id_facturacion BIGINT NOT NULL,
    s_uuid_factura_ingreso VARCHAR(2000) NULL,
    s_uuid_complemento_pago VARCHAR(2000) NULL,
    s_origen_pago VARCHAR(40) NOT NULL,
    n_id_pago_origen BIGINT NOT NULL,
    n_parcialidad INT NOT NULL,
    s_forma_pago_sat VARCHAR(10) NULL,
    s_descripcion_forma_pago VARCHAR(255) NULL,
    n_monto_pagado DECIMAL(18,2) NULL,
    n_saldo_anterior DECIMAL(18,2) NULL,
    n_saldo_insoluto DECIMAL(18,2) NULL,
    d_fecha_pago DATETIME NULL,
    s_proveedor VARCHAR(60) NULL,
    s_estado VARCHAR(120) NULL,
    n_estatus INT NULL,
    s_xml_timbrado LONGTEXT NULL,
    s_codigo_error VARCHAR(120) NULL,
    s_error_pac VARCHAR(2000) NULL,
    s_correlation_id VARCHAR(120) NULL,
    d_fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (n_id),
    KEY idx_tw_facturacion_complemento_pago_venta (n_id_venta),
    KEY idx_tw_facturacion_complemento_pago_factura (n_id_facturacion),
    KEY idx_tw_facturacion_complemento_pago_uuid_ingreso (s_uuid_factura_ingreso(255)),
    KEY idx_tw_facturacion_complemento_pago_uuid_rep (s_uuid_complemento_pago(255)),
    KEY idx_tw_facturacion_complemento_pago_origen (n_id_venta, s_origen_pago, n_id_pago_origen)
);