CREATE TABLE IF NOT EXISTS tw_pago_cliente (
    n_id BIGINT NOT NULL AUTO_INCREMENT,
    n_id_cliente BIGINT NOT NULL,
    n_id_dato_factura BIGINT NOT NULL,
    d_fecha_registro DATETIME NOT NULL,
    d_fecha_pago DATETIME NOT NULL,
    n_importe_total DECIMAL(18,2) NOT NULL,
    n_importe_aplicado DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    n_importe_disponible DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    s_moneda VARCHAR(10) NOT NULL DEFAULT 'MXN',
    n_id_forma_pago BIGINT NOT NULL,
    s_forma_pago_sat VARCHAR(10) NULL,
    s_descripcion_forma_pago VARCHAR(120) NULL,
    s_referencia VARCHAR(255) NULL,
    s_numero_autorizacion VARCHAR(255) NULL,
    s_folio_operacion VARCHAR(255) NULL,
    s_clave_rastreo VARCHAR(255) NULL,
    s_banco_origen VARCHAR(255) NULL,
    s_cuenta_origen VARCHAR(255) NULL,
    s_ultimos4_cuenta_origen VARCHAR(10) NULL,
    s_banco_destino VARCHAR(255) NULL,
    s_cuenta_destino VARCHAR(255) NULL,
    s_ultimos4_cuenta_destino VARCHAR(10) NULL,
    s_titular_cuenta VARCHAR(255) NULL,
    s_terminal VARCHAR(255) NULL,
    s_numero_voucher VARCHAR(255) NULL,
    s_ultimos4_tarjeta VARCHAR(10) NULL,
    s_tipo_tarjeta VARCHAR(100) NULL,
    s_red_tarjeta VARCHAR(100) NULL,
    s_comprobante_url VARCHAR(500) NULL,
    s_observaciones TEXT NULL,
    n_id_usuario_registro BIGINT NOT NULL,
    n_id_caja BIGINT NULL,
    n_id_corte_caja BIGINT NULL,
    s_estatus VARCHAR(60) NOT NULL,
    d_fecha_conciliacion DATETIME NULL,
    n_conciliado TINYINT(1) NOT NULL DEFAULT 0,
    n_estatus INT NOT NULL DEFAULT 1,
    PRIMARY KEY (n_id),
    KEY idx_tw_pago_cliente_cliente (n_id_cliente),
    KEY idx_tw_pago_cliente_dato_factura (n_id_dato_factura),
    KEY idx_tw_pago_cliente_forma_pago (n_id_forma_pago),
    KEY idx_tw_pago_cliente_usuario (n_id_usuario_registro),
    KEY idx_tw_pago_cliente_caja (n_id_caja),
    KEY idx_tw_pago_cliente_estatus (s_estatus)
);