CREATE TABLE IF NOT EXISTS tw_pago_aplicacion (
    n_id BIGINT NOT NULL AUTO_INCREMENT,
    n_id_pago_cliente BIGINT NOT NULL,
    n_id_cliente BIGINT NOT NULL,
    n_id_venta BIGINT NOT NULL,
    n_id_facturacion BIGINT NULL,
    n_id_dato_factura BIGINT NOT NULL,
    n_monto_aplicado DECIMAL(18,2) NOT NULL,
    n_saldo_anterior DECIMAL(18,2) NOT NULL,
    n_saldo_insoluto DECIMAL(18,2) NOT NULL,
    n_parcialidad INT NULL,
    s_estatus VARCHAR(60) NOT NULL,
    d_fecha_aplicacion DATETIME NOT NULL,
    n_id_usuario BIGINT NOT NULL,
    n_orden_aplicacion INT NOT NULL DEFAULT 1,
    s_origen_registro VARCHAR(60) NOT NULL,
    n_estatus INT NOT NULL DEFAULT 1,
    PRIMARY KEY (n_id),
    KEY idx_tw_pago_aplicacion_pago (n_id_pago_cliente),
    KEY idx_tw_pago_aplicacion_cliente (n_id_cliente),
    KEY idx_tw_pago_aplicacion_venta (n_id_venta),
    KEY idx_tw_pago_aplicacion_facturacion (n_id_facturacion),
    KEY idx_tw_pago_aplicacion_estatus (s_estatus)
);